Profile model extra props and profile edit view
hatchways/team-pine-cone pull request #81
Opened 2020-10-28 13:56 UTC by Braagaa

**What it does:**

- Extra props are needed in the Profile model in order to search and filter sitters. These are ratings, hourly rate, and an extra prop job title
- Job title will be a list of jobs the sitter is more inclined too such as dog trainer, dog sitter, dog walker, etc
- Profile Edit view also has a condition for when it is a sitter. It will get 2 extra fields. One is to input their hourly rate and the second is to select their job titile.
- Update Profile Edit now uses @dproc96 Profile Context

2020-10-28 14:20 UTC, dproc96 approved these changes
This looks good to me! Nice additions

2020-10-28 14:20 UTC, dproc96 commented on client/src/components/ProfileEdit/data.js
> +export const jobTitles = [
Interesting addition to the app, I like this idea for expanding the market

2020-10-28 14:20 UTC, dproc96 commented on client/src/components/ProfileEdit/index.js
> +      .then(({ profile }) => setProfile(profile))
This is a much better way of doing what I did in my PR for the Dog Sitter switch. Once this is merged we can use this instead!

2020-10-28 19:22 UTC, dahrk commented on client/src/components/ProfileEdit/index.js
> +  const handleEmail = regExHandler(/.+@.+..+/, "Email is not valid", "email");
This regex evaluator misses a few cases, i.e. tony@test passes the validation. There are some more robust regex checks for email online that we can refer from

2020-10-28 19:22 UTC, dahrk commented on client/src/components/ProfileEdit/index.js
> +    /^\d*(\.\d{0,2})?$/,
29123. will pass this check, might be good to append 00 to the end

2020-10-28 19:30 UTC, dahrk commented on client/src/components/ProfileEdit/index.js
>        .then(() => setIsSaved(true));
You'll likely have to update the user.context as well. A changed email does not show on the front end until the app is refreshed

2020-10-28 19:38 UTC, dahrk commented on client/src/components/ProfileEdit/index.js
> +  const handlePhone = (value) => {
Is it possible to make this also work with regExHandler?

2020-10-28 19:39 UTC, dahrk commented on client/src/components/ProfileEdit/index.js
> +      {profile && profile.isSitter && (
This and l252 can probably be wrapped together in case anything chances with the variables

2020-10-28 19:40 UTC, dahrk requested changes
Lets make sure that email is updated in user.context before merging this one

2020-10-30 20:26 UTC, dahrk approved these changes
Functionality is working but the profileContext is not being updated on editProfile until the page is refreshed. At a glance you may have to use setProfile(cleanForm) instead of setProfile(profile)

Approving because you need this for another branch, make the profile change before merge

2020-10-30 22:24 UTC, merged